answers:
  outputs:
    dev:
      dataset: dbt_carlos
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: daring-charmer-384315
      threads: 60
      type: bigquery

    production:
      dataset: dbt_production
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: daring-charmer-384315
      threads: 60
      type: bigquery      
  target: dev
