lessions:
  outputs:
    dev:
      dataset: dbt_jian
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: key-chalice-387215
      threads: 60
      type: bigquery
  target: dev
